name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta todos los días a la medianoche (UTC)
  workflow_dispatch:     # Permite ejecución manual

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Generar Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: olvisking20
          outputs: |
            ./dist/github-contribution-grid-snake.svg

      - name: Publicar en rama output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true

