name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # todos los días a la medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Generar snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: olvisking20
          outputs: |
            ./dist/github-contribution-grid-snake.svg

      - name: Subir a rama output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
